import { SessionQuiz } from './types';

export const SESSION_QUIZZES: Record<string, SessionQuiz> = {
  'session-1': {
    sessionId: 'session-1',
    title: 'Session 1 Concept Check: Qiskit & Quantum Foundations',
    passingScore: 75,
    questions: [
      {
        id: 's1-q1',
        question:
          'Applying a Hadamard (H) gate to the ground state |0⟩ produces which quantum state vector?',
        options: [
          '|1⟩',
          '(|0⟩ + |1⟩) / √2',
          '(|0⟩ - |1⟩) / √2',
          '|0⟩ with 100% probability',
        ],
        correctIndex: 1,
        explanation:
          'The Hadamard gate maps the basis state |0⟩ into the equal superposition state |+⟩ = (|0⟩ + |1⟩)/√2.',
      },
      {
        id: 's1-q2',
        question:
          'In Qiskit 1.2+, which Primitives V2 class is specifically designed to evaluate the expectation values of physical observables (like Hamiltonians)?',
        options: ['SamplerV2', 'EstimatorV2', 'PassManager', 'BackendV2'],
        correctIndex: 1,
        explanation:
          'EstimatorV2 computes expectation values of observables (represented as SparsePauliOp), whereas SamplerV2 generates quasi-probability bitstring distributions.',
      },
      {
        id: 's1-q3',
        question:
          'What is the state generated by applying a Hadamard gate on qubit 0 followed by a CNOT with control qubit 0 and target qubit 1, starting from |00⟩?',
        options: [
          '(|00⟩ + |11⟩) / √2 (Bell state |Φ+⟩)',
          '(|01⟩ + |10⟩) / √2 (Bell state |Ψ+⟩)',
          '|11⟩',
          '(|00⟩ - |11⟩) / √2',
        ],
        correctIndex: 0,
        explanation:
          'Hadamard on qubit 0 creates (|0⟩+|1⟩)/√2 ⊗ |0⟩ = (|00⟩+|10⟩)/√2. The subsequent CNOT flips the target qubit when the control is 1, creating the maximally entangled Bell state (|00⟩+|11⟩)/√2.',
      },
      {
        id: 's1-q4',
        question:
          'What happens to a qubit in superposition state α|0⟩ + β|1⟩ upon computational basis measurement?',
        options: [
          'It remains in superposition with preserved phase',
          'It collapses to |0⟩ with probability |α|² or to |1⟩ with probability |β|²',
          'It always outputs 0.5',
          'It clones the state to an auxiliary register',
        ],
        correctIndex: 1,
        explanation:
          'According to the measurement postulate of quantum mechanics, the wavefunction irreversibly collapses onto one of the eigenbasis states with probabilities given by the Born rule: P(0) = |α|² and P(1) = |β|².',
      },
      {
        id: 's1-q5',
        question: 'What is the effect of applying the Pauli-Z gate to the |1⟩ state?',
        options: [
          'It flips it to |0⟩',
          'It adds a global phase of i',
          'It adds a relative phase of -1, producing -|1⟩',
          'It creates a superposition state',
        ],
        correctIndex: 2,
        explanation: 'The Pauli-Z gate applies a phase shift of π to the |1⟩ state, effectively multiplying it by -1, while leaving the |0⟩ state unchanged.',
      },
      {
        id: 's1-q6',
        question: 'In a quantum circuit, what is the purpose of a barrier instruction?',
        options: [
          'To entangle all qubits simultaneously',
          'To prevent the transpiler from optimizing or combining gates across the barrier',
          'To physically shield qubits from thermal noise',
          'To apply a classical IF conditional logic',
        ],
        correctIndex: 1,
        explanation: 'The barrier acts as a directive to the Qiskit transpiler, preventing it from commuting, commuting, or merging gates across that point, which is useful for structural isolation and debugging.',
      }
    ],
  },
  'session-2': {
    sessionId: 'session-2',
    title: 'Session 2 Concept Check: Quantum Materials & Simulation',
    passingScore: 75,
    questions: [
      {
        id: 's2-q1',
        question:
          'Why are classical supercomputers fundamentally limited when simulating strongly correlated electronic materials?',
        options: [
          'Because classical computers cannot represent floating-point numbers',
          'The Hilbert space dimension of an N-electron system grows exponentially as 2^N (or 4^N with spin)',
          'Fermions cannot be mathematically written in Python',
          'Classical computers cannot calculate eigenvalues',
        ],
        correctIndex: 1,
        explanation:
          'Quantum many-body state spaces scale exponentially with system size (O(2^N)), demanding impossible memory and compute overhead on classical Von Neumann architectures.',
      },
      {
        id: 's2-q2',
        question:
          'What is the purpose of the Jordan-Wigner transformation in electronic structure quantum simulation?',
        options: [
          'To convert classical data into floating point values',
          'To map fermionic creation and annihilation operators obeying anti-commutation relations onto spin-1/2 Pauli operators',
          'To increase processor clock speed',
          'To bypass the no-cloning theorem',
        ],
        correctIndex: 1,
        explanation:
          'Fermionic creation and annihilation operators satisfy canonical anti-commutation relations. The Jordan-Wigner transformation maps these onto Pauli spin strings (X, Y, Z) that can be directly executed on qubit circuits.',
      },
      {
        id: 's2-q3',
        question:
          'What is the objective function minimized by the classical optimizer in the Variational Quantum Eigensolver (VQE)?',
        options: [
          'The gate execution runtime',
          'The energy expectation value ⟨ψ(θ)|H|ψ(θ)⟩',
          'The number of qubits in the circuit',
          'The transpilation level',
        ],
        correctIndex: 1,
        explanation:
          'VQE is governed by the Rayleigh-Ritz variational principle: the expectation value ⟨ψ(θ)|H|ψ(θ)⟩ provides an upper bound to the ground-state energy E_0, which the classical optimizer minimizes.',
      },
      {
        id: 's2-q4',
        question:
          'In hardware-efficient ansatze (e.g. RealAmplitudes), why are parameterized single-qubit rotations interleaved with native entanglers?',
        options: [
          'To create deep circuits that crash the backend',
          'To span the target Hilbert subspace while respecting physical hardware coupling and native gate sets without high SWAP penalties',
          'To convert the simulation into classical machine learning',
          'To avoid measuring qubits',
        ],
        correctIndex: 1,
        explanation:
          'Hardware-efficient ansatze restrict two-qubit entangling gates strictly to the physically connected hardware edges, avoiding expensive SWAP chains while parameterizing single-qubit Ry/Rz rotations.',
      },
      {
        id: 's2-q5',
        question: 'What is the primary objective of the Variational Quantum Eigensolver (VQE)?',
        options: [
          'To factor large prime numbers exponentially faster',
          'To approximate the lowest energy eigenvalue (ground state) of a given Hamiltonian',
          'To perform quantum teleportation across a network',
          'To compile classical code into quantum assembly',
        ],
        correctIndex: 1,
        explanation: 'VQE uses a parameterized quantum circuit and a classical optimizer (hybrid approach) to minimize the expectation value of a Hamiltonian, finding an upper bound to its ground state energy.',
      },
      {
        id: 's2-q6',
        question: 'How does the Trotter-Suzuki decomposition enable quantum Hamiltonian simulation?',
        options: [
          'By splitting the exponential of a sum of non-commuting operators into a product of short-time exponentials that can be mapped to quantum gates',
          'By converting all fermionic operators into classical bits',
          'By increasing the physical temperature of the qubits',
          'By using Shor’s algorithm to factor the Hamiltonian matrix',
        ],
        correctIndex: 0,
        explanation: 'Since many Hamiltonian terms do not commute, Trotterization approximates e^{-i(A+B)t} as (e^{-iAt/n} e^{-iBt/n})^n, allowing the simulation to be built from native rotation gates.',
      }
    ],
  },
  'session-3': {
    sessionId: 'session-3',
    title: 'Session 3 Concept Check: Qubit Connectivity & Architecture',
    passingScore: 75,
    questions: [
      {
        id: 's3-q1',
        question:
          'Why does a 1D linear nearest-neighbor architecture incur high SWAP overhead for long-range two-qubit interactions?',
        options: [
          'Because linear processors do not support single-qubit gates',
          'Two-qubit gates can only execute between adjacent physical qubits, requiring O(N) SWAP gates to bring distant qubits together',
          'Linear processors have 0% gate fidelity',
          'The transpiler disables optimization on linear chains',
        ],
        correctIndex: 1,
        explanation:
          'In a linear chain, physical connectivity is strictly degree-2. Interacting non-adjacent qubits requires inserting sequences of SWAP gates, inflating two-qubit gate count and circuit depth.',
      },
      {
        id: 's3-q2',
        question:
          'What key advantage does the heavy-hex lattice topology offer in superconducting quantum systems compared to high-degree square lattices?',
        options: [
          'It completely eliminates all two-qubit gate errors',
          'It reduces frequency collisions and parasitic crosstalk by limiting vertex degree to 2 and 3',
          'It guarantees zero SWAP insertions for arbitrary graphs',
          'It allows infinite coherence times (T1 = ∞)',
        ],
        correctIndex: 1,
        explanation:
          'Heavy-hex topology limits connectivity to degree-2 and degree-3 vertices, which substantially suppresses parasitic ZZ crosstalk and microwave frequency collisions across multi-qubit chips.',
      },
      {
        id: 's3-q3',
        question:
          'How many native CNOT (CX) gates are typically required to implement a single SWAP gate on superconducting architectures?',
        options: ['1 CX gate', '2 CX gates', '3 CX gates', '4 CX gates'],
        correctIndex: 2,
        explanation:
          'A SWAP gate decomposes into 3 alternating CNOT gates (CX_01, CX_10, CX_01), tripling the two-qubit gate error penalty for every routing step.',
      },
      {
        id: 's3-q4',
        question:
          'Which Qiskit transpiler routing algorithm uses a heuristic look-ahead mechanism to minimize SWAP insertions?',
        options: ['TrivialRouting', 'SabreSwap', 'LinearSweep', 'UnitarySynthesis'],
        correctIndex: 1,
        explanation:
          'SabreSwap (SWAP-based Bounded-depth Heuristic) evaluates a look-ahead window of future circuit gates to choose routing SWAPs that minimize overall circuit depth.',
      },
      {
        id: 's3-q5',
        question: 'What is the primary role of the PassManager in Qiskit?',
        options: [
          'To execute the final circuit on cloud hardware',
          'To authenticate the user’s IBM Quantum credentials',
          'To define a custom sequence of transpilation passes for circuit optimization and hardware routing',
          'To manage quantum state vectors in memory',
        ],
        correctIndex: 2,
        explanation: 'The PassManager orchestrates a pipeline of transpiler passes (like layout, routing, translation, and optimization) to tailor a logical circuit to a specific backend topology.',
      },
      {
        id: 's3-q6',
        question: 'Which of these best describes T1 relaxation time in superconducting qubits?',
        options: [
          'The time it takes for a qubit to lose its phase coherence without losing energy',
          'The characteristic time for a qubit in the excited |1⟩ state to decay to the ground |0⟩ state via energy loss',
          'The execution time of a single CNOT gate',
          'The time taken to cool the cryostat',
        ],
        correctIndex: 1,
        explanation: 'T1 (longitudinal relaxation time) measures amplitude damping—the time scale over which a qubit loses energy to its environment and decays from |1⟩ to |0⟩.',
      }
    ],
  },
  'session-4': {
    sessionId: 'session-4',
    title: 'Session 4 Concept Check: Quantum Optics & Sensing',
    passingScore: 75,
    questions: [
      {
        id: 's4-q1',
        question:
          'What fundamental precision limit scales as 1/√N with N photons/particles, known as the Standard Quantum Limit (SQL)?',
        options: [
          'The Heisenberg limit',
          'The Shot-noise limit',
          'The Planck limit',
          'The Nyquist rate',
        ],
        correctIndex: 1,
        explanation:
          'Classical and uncorrelated quantum measurements are bounded by the shot-noise limit scaling as 1/√N. Entangled quantum states (e.g. squeezed or NOON states) can surpass this up to the Heisenberg limit (1/N).',
      },
      {
        id: 's4-q2',
        question:
          'Why are Nitrogen-Vacancy (NV) centers in diamond exceptionally well-suited for nanoscale quantum sensing?',
        options: [
          'They cannot sense magnetic fields',
          'They possess optically addressable electronic spin states with long coherence times even at room temperature',
          'They can only operate at absolute zero (0 Kelvin)',
          'They emit classical radio frequencies only',
        ],
        correctIndex: 1,
        explanation:
          'NV centers in diamond have atomic-scale spatial resolution and long spin coherence times ($T_2$) at ambient room temperature, allowing optical spin initialization and readout (ODMR) for magnetic and thermal sensing.',
      },
      {
        id: 's4-q3',
        question:
          'In quantum phase estimation for optical sensing, how does entanglement improve phase uncertainty Δφ?',
        options: [
          'By scaling Δφ down to O(1/N) (Heisenberg scaling)',
          'By increasing the circuit error rate',
          'By converting phase into classical heat',
          'It provides no improvement over classical methods',
        ],
        correctIndex: 0,
        explanation:
          'Using entangled N-particle states (like NOON states (|N,0⟩ + |0,N⟩)/√2), the phase sensitivity scales with the ultimate physical bound: Δφ ~ 1/N, an N-fold precision improvement over independent particles.',
      },
      {
        id: 's4-q4',
        question:
          'What technique is commonly used to optically initialize and read out NV center spin states?',
        options: [
          'Optically Detected Magnetic Resonance (ODMR)',
          'Classical Fourier Transform',
          'Cathode Ray Emission',
          'Gas Chromatography',
        ],
        correctIndex: 0,
        explanation:
          'Optically Detected Magnetic Resonance (ODMR) uses green laser excitation (532 nm) and microwave frequency sweeps to detect fluorescence changes between ms=0 and ms=±1 spin states.',
      },
      {
        id: 's4-q5',
        question: 'What is the Standard Quantum Limit (SQL) for phase estimation when using N independent, unentangled particles?',
        options: [
          'Δφ ~ 1/N',
          'Δφ ~ 1/N²',
          'Δφ ~ 1/√N',
          'Δφ ~ e^(-N)',
        ],
        correctIndex: 2,
        explanation: 'Without entanglement, N independent probes provide a statistical precision scaling of 1/√N (the shot-noise limit or SQL), as dictated by classical probability.',
      },
      {
        id: 's4-q6',
        question: 'Which technique is used in Ramsey interferometry to measure small static magnetic fields?',
        options: [
          'Mapping the accumulated quantum phase (acquired over time t) into measurable population differences',
          'Measuring the physical temperature change of the diamond',
          'Using a classical hall-effect sensor',
          'Executing Shor’s algorithm',
        ],
        correctIndex: 0,
        explanation: 'In a Ramsey sequence (π/2 - wait - π/2), the qubit accumulates a relative phase proportional to the magnetic field during the free precession time, which the second π/2 pulse converts into a measurable Z-basis probability.',
      }
    ],
  },
  'session-5': {
    sessionId: 'session-5',
    title: 'Session 5 Concept Check: Quantum Machine Learning',
    passingScore: 75,
    questions: [
      {
        id: 's5-q1',
        question:
          'What is the primary role of a quantum feature map (such as ZZFeatureMap) in quantum classification?',
        options: [
          'To compress the dataset into a single bit',
          'To non-linearly embed classical feature vectors into high-dimensional quantum Hilbert space states |Φ(x)⟩',
          'To eliminate the need for classical data preprocessing',
          'To convert quantum circuits into convolutional neural networks',
        ],
        correctIndex: 1,
        explanation:
          'A quantum feature map applies unitary transformations parameterized by input data $x$, projecting classical inputs non-linearly into high-dimensional Hilbert space where complex patterns become linearly separable.',
      },
      {
        id: 's5-q2',
        question:
          'What phenomenon causes the variance of gradients in random deep parameterized quantum circuits to vanish exponentially with the number of qubits?',
        options: [
          'Overfitting',
          'Barren plateaus',
          'Exploding gradients',
          'Aliasing',
        ],
        correctIndex: 1,
        explanation:
          'Barren plateaus occur when the gradients of cost functions vanish exponentially in $N$ ($Var[∂C/∂θ] ~ O(2^{-N})$), making gradient-based training impossible without local cost functions or structured initializations.',
      },
      {
        id: 's5-q3',
        question:
          'In a Quantum Support Vector Classifier (QSVC), how is the quantum kernel matrix element K(x_i, x_j) computed?',
        options: [
          'By taking the classical dot product x_i · x_j',
          'By evaluating the fidelity overlap |⟨Φ(x_i)|Φ(x_j)⟩|² using a quantum circuit',
          'By training a deep neural network on a GPU',
          'By counting the number of CNOT gates in the circuit',
        ],
        correctIndex: 1,
        explanation:
          'The quantum kernel evaluates the transition probability / fidelity between quantum feature states: $K(x_i, x_j) = |⟨0|U^†(x_j) U(x_i)|0⟩|² = |⟨Φ(x_j)|Φ(x_i)⟩|²$.',
      },
      {
        id: 's5-q4',
        question:
          'How does hardware connectivity affect the evaluation of ZZFeatureMap entangling blocks?',
        options: [
          'Coupling topology has no effect on two-qubit gates',
          'Non-adjacent qubit entanglers require SWAP routing passes that increase circuit depth and introduce noise into kernel evaluations',
          'It speeds up execution linearly',
          'It automatically cures barren plateaus',
        ],
        correctIndex: 1,
        explanation:
          'The entangling layer of ZZFeatureMaps includes RZZ interactions. On constrained topologies (like linear or heavy-hex), non-local RZZ terms require SWAP routing, inflating depth and fidelity errors.',
      },
      {
        id: 's5-q5',
        question: 'What is the role of the parameterized ansatz in a Variational Quantum Classifier (VQC)?',
        options: [
          'To act as a fixed random feature map',
          'To apply trainable rotation and entanglement gates whose parameters are optimized to separate classes',
          'To permanently store the training dataset',
          'To execute Shor’s algorithm',
        ],
        correctIndex: 1,
        explanation: 'The ansatz serves as the trainable part of the model (akin to neural network weights). The classical optimizer iteratively updates its rotation angles to minimize the classification loss.',
      },
      {
        id: 's5-q6',
        question: 'How does a Quantum Support Vector Machine (QSVM) utilize a quantum computer?',
        options: [
          'By training the classical SVM weights entirely on quantum hardware',
          'By using a quantum circuit to compute the inner product (kernel) between data points mapped to a quantum Hilbert space',
          'By replacing the classical CPU with a QPU for all OS tasks',
          'By using Grover’s algorithm to search for the best hyperparameter',
        ],
        correctIndex: 1,
        explanation: 'A QSVM delegates only the kernel matrix evaluation K(x_i, x_j) to the quantum computer, passing the resulting matrix back to a standard classical SVM optimizer.',
      }
    ],
  },
  'session-6': {
    sessionId: 'session-6',
    title: 'Session 6 Concept Check: Quantum Cryptography & Cyber Security',
    passingScore: 75,
    questions: [
      {
        id: 's6-q1',
        question:
          'Which mathematical problem underlying RSA encryption does Shor’s algorithm solve in polynomial time on a fault-tolerant quantum computer?',
        options: [
          'Integer factorization via quantum order finding',
          'Symmetric block cipher substitution',
          'SHA-256 hash collision generation',
          'Graph coloring',
        ],
        correctIndex: 0,
        explanation:
          'Shor’s algorithm computes the period $r$ of $a^x \\pmod N$ in $O((\\log N)^3)$ time using the Quantum Fourier Transform (QFT), efficiently breaking RSA integer factorization.',
      },
      {
        id: 's6-q2',
        question:
          'What is the primary architectural bottleneck when compiling Shor’s modular arithmetic on physical hardware?',
        options: [
          'Lack of single-qubit Pauli-X gates',
          'Deep reversible carry chains in modular addition and exponentiation requiring long routing SWAP sequences',
          'Classical computers cannot compile Python code',
          'Qiskit does not support modular math',
        ],
        correctIndex: 1,
        explanation:
          'Reversible modular addition and multiplication circuits require sequential carry propagation chains across all bits, creating tight dependencies and massive SWAP overhead on constrained planar topologies.',
      },
      {
        id: 's6-q3',
        question:
          'Which post-quantum cryptographic algorithm was standardized by NIST in 2024 as FIPS 203 for general key encapsulation (ML-KEM)?',
        options: ['CRYSTALS-Kyber', 'RSA-4096', 'ECDSA P-384', 'DES'],
        correctIndex: 0,
        explanation:
          'NIST standardized CRYSTALS-Kyber as ML-KEM (Module-Lattice Key Encapsulation Mechanism) in FIPS 203 as the premier post-quantum key establishment standard.',
      },
      {
        id: 's6-q4',
        question:
          'By what factor does Grover’s algorithm speed up brute-force attacks against symmetric encryption (AES-256)?',
        options: [
          'Exponential speedup (solves in seconds)',
          'Quadratic speedup (reducing 256-bit effective security to 128-bit)',
          'Polynomial speedup of degree 10',
          'No speedup whatsoever',
        ],
        correctIndex: 1,
        explanation:
          'Grover’s quantum search provides a quadratic speedup ($O(\\sqrt{N})$), effectively halving the key length security level (e.g. AES-256 offers 128 bits of quantum security).',
      },
      {
        id: 's6-q5',
        question: 'What principle guarantees the security of Quantum Key Distribution (QKD) protocols like BB84?',
        options: [
          'The computational difficulty of factoring large primes',
          'The no-cloning theorem and the fact that measurement disturbs a quantum state, revealing any eavesdropper',
          'The speed of light',
          'Symmetric block encryption',
        ],
        correctIndex: 1,
        explanation: 'Unlike classical cryptography which relies on unproven mathematical hardness, QKD relies on quantum physics: an eavesdropper cannot copy unknown quantum states (no-cloning) and intercepting them introduces detectable errors.',
      },
      {
        id: 's6-q6',
        question: 'Which approach to post-quantum cryptography is based on the difficulty of finding the shortest vector in a high-dimensional grid?',
        options: [
          'Isogeny-based cryptography',
          'Hash-based signatures',
          'Lattice-based cryptography',
          'Multivariate polynomials',
        ],
        correctIndex: 2,
        explanation: 'Lattice-based cryptography (including NIST winners like CRYSTALS-Kyber/Dilithium) relies on the Shortest Vector Problem (SVP) and Learning With Errors (LWE), which are believed to be hard even for quantum computers.',
      }
    ],
  },
};
